In [1]:
import numpy as np # we import numpy and rename it as np 

a = np.array([[1,2],[3,4]]) # array is the one we can use to build a matrix 

In [2]:
a # because is 2 by 2 matrix, so there are two braskets infront of the elements 

array([[1, 2],
       [3, 4]])

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # size is 3 * 3 

In [7]:
A.shape # check the shape of A

(3, 3)

In [12]:
# vector is a special type of matrix ： the size of vector is 1 by n, only one row 
v1 = np.array([[1,2,3]])

In [15]:
# if we have v1, and we have A 
A2 = np.vstack([v1, v1]) # v stands for vertical. vstack means vertically stack two vectors/matrix 

In [18]:
A3 = np.hstack([v1, v1])

In [21]:
# column vector 
v2 = np.array([[1],[2],[3]])

In [25]:
# what whill happen if we stack two v2
A3 = np.hstack([v2, v2])

In [28]:
A4 = np.hstack([A,A]) # 3 * 6 

### Elementary Extraction

In [33]:
# If I want the first row ? 
A4[0, :] # first row starts from 0, : means I want all columns 

array([1, 2, 3, 1, 2, 3])

In [34]:
# If I want the first column 
A4[:, 0] # first column

array([1, 4, 7])

In [40]:
# What happends if I want two rows or two columns? 
A4[:, 3:5] # Notice, 3:5 only gives us the forth and fifth columns, since the end number 5 does not work 

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
A4[3:5,:] # if the index number over the shape of the matrix, we will get noting

array([], shape=(0, 6), dtype=int64)

In [44]:
# if I want the second, third, forth rows and the second, third, forth columns? 
A4[1:4, 1:4]

array([[5, 6, 4],
       [8, 9, 7]])

### Special function for building matrix

In [46]:
z = np.zeros((3,2)) # initialize a zero matrix

In [48]:
o = np.ones((4,2)) # matrix with all 1 elementary

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
f = np.full(3,4) # a vector with three elements 

In [53]:
e = np.eye(4) # this is used to build an identical matrix, 4 * 4 

In [55]:
d = np.diag([1,2,3]) # diagnal matrix

In [57]:
# do it by yourself! challenge 1! 
# using diagnal matrix, ones, and matrix operation
np.ones((10,10))*5 - np.eye(10)*5 
np.ones((10,10))*5 - np.diag([5,5,5,5,5,5,5,5,5,5])

array([[0., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 0., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 0., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 0., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 0., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 0., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 0., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 0., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 0., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 0.]])

### Matrix Operations 

In [68]:
# Matrix product, matrix multiplication 
# The columns of A is as same as the row of v2, then we can do the matrix multiplication
M = A.dot(v2)

In [76]:
s = v1.dot(v2) # 1 * 1 

In [83]:
# Transpose change the shape of v1 from (1,3) to (3,1) 
At = A.T

In [85]:
v2t = v1.dot(v2)

In [87]:
v2tv2 = v2.T.dot(v2)

In [89]:
Av2 = A.dot(v2)
AAt = A.dot(A.T)

In [91]:
# Elementwise multiplication 
A_At = np.multiply(A, A.T) 

In [94]:
A_v2 = np.multiply(A, v2) # normally, A and v2 should be in the same type. But why we can do it here? 

In [95]:
# When two matrix are not in the same type, this may triage an important feature in numpy, which is called 
# broadcast 
# First, numpy boradcasts the vector [1,2,3] to match the shape of matrix A.
# [1,2,3] -> [[1,1,1],[2,2,2],[3,3,3]]
# Then it performs element-wise multiplication between the broadcasted vector and the matrix! 

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [101]:
# determinant 
# Only the matrix has the same row and columns can calculate the determinant. 2*2 , 3*3 
# If a matrix can calculate the determinant, then we call it invertiable. Also the determinant should be non-zeros. 
# A matrix is an array. The output of the determinant is a number
detA = np.linalg.det(A)

In [106]:
B = np.array([[1,2,3],[4,6,7], [7,8,13]])
np.linalg.det(B) # B is invertible! 

np.float64(-14.000000000000004)

In [107]:
# If the matrix B is invertible, that means inverse B does not exists! 

In [108]:
# Matrix Decomposition! 

In [109]:
# SVD : singular value decompostion 

In [111]:
U, S, Vtranspose = np.linalg.svd(A4) # Output of S is a diagnal matrix

In [116]:
U.dot(U.T) # the special feature of U and V is UU^T = I and VV^t = I

array([[ 1.00000000e+00, -3.42794760e-16,  5.80857168e-17],
       [-3.42794760e-16,  1.00000000e+00, -1.96634278e-16],
       [ 5.80857168e-17, -1.96634278e-16,  1.00000000e+00]])

In [119]:
# hits : first build the coefficent matrix 
Z = np.array([[5, -2, 3], [4,1,1], [0, -3, 2]]) 
y = np.array([3,0,1])
# second: calculate the inverse of Z
# third : multiply z_inv with y
# we want to solve Z*x = y. The answer is x = Z^-1*y
# A*b not equal to  b*A !!!!!!!!!!!!!!!!!!!!
x = np.linalg.inv(Z).dot(y)

In [121]:
Z.dot(x) # check if our answer is correct, if the answer is as same as y, we are correct! 

array([ 3.00000000e+00, -3.55271368e-15,  1.00000000e+00])

In [122]:
# Challenge 2
# y = f(w.T*x) 
# w = [-1,2,3] # w is 1 * 3 
# x = [1,1,1]  # x is 1 * 3 
# First step: define the function f 
# second step : take w.T times x as input 

In [126]:
# def is the key words for defining a function 
# the blue one sigmoid is the name of the function 
# (x) stands for the input
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))
# neuron is f
def neuron(x, w):
    return(sigmoid(x.dot(w)))
x = np.array([1,1,1])
w = np.array([-1,2,3])

In [127]:
neuron(x, w)

0.9820137900379085